insert into DEMO_SCHEMA_TYPE (ACCOUNT_TYPE_ID,MNEMONIC,ACCOUNT_TYPE_NAME,CREATION_DATE)
values(50000,'MILES','Miles',TO_DATE('2020/01/01','YYYY/MM/DD'));
insert into DEMO_SCHEMA_TYPE(ACCOUNT_TYPE_ID,MNEMONIC,ACCOUNT_TYPE_NAME,CREATION_DATE)
values(50001,'Play','Game Play',TO_DATE('2021/03/01','YYYY/MM/DD'));
